name: Build and Deploy

# Triggered by going to https://github.com/<name>/native-utils/releases and creating a release.
on:
  release:
    types:
    - published

jobs:

  build_and_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7

    - name: Build and deploy
      run: mvn -B install source:jar deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: target/native-utils-1.0.jar
        path: target/native-utils-1.0-sources.jar
