name: Build

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7

    - name: Build
      run: mvn -B install source:jar --file pom.xml

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: target/native-utils-1.0.jar
        path: target/native-utils-1.0-sources.jar
